import type { ReactElement } from "react";
import {
  SiReact,
  SiTypescript,
  SiRedux,
  SiFirebase,
  SiTailwindcss,
  SiVite,
  SiGithub,
  SiPostman,
  SiFigma,
  SiExpo,
  SiJavascript,
  SiXcode,
  SiAndroidstudio,
  SiGraphql,
  SiShopify,
  SiFramer,
  SiShadcnui,
  SiNodedotjs,
  SiHtml5,
  SiCss,
  SiGit,
  SiGooglecloud,
} from "react-icons/si";
import { TbBrandReactNative } from "react-icons/tb";
import { FiZap, FiTool, FiCloud, FiCode } from "react-icons/fi";
import { MdAnimation } from "react-icons/md";

export const skillIconUrls: Record<string, string> = {
  reactnative: "https://reactnative.dev",
  react: "https://react.dev",
  javascript:
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  typescript: "https://www.typescriptlang.org",
  redux: "https://redux-toolkit.js.org",
  firebase: "https://firebase.google.com",
  tailwind: "https://tailwindcss.com",
  github: "https://github.com",
  figma: "https://www.figma.com",
  postman: "https://www.postman.com",
  expo: "https://expo.dev",
  vite: "https://vitejs.dev",
  api: "https://developer.mozilla.org/en-US/docs/Web/HTTP",
  websocket:
    "https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API",
  xcode: "https://developer.apple.com/xcode/",
  androidstudio: "https://developer.android.com/studio",
  graphql: "https://graphql.org",
  shopify: "https://shopify.dev/docs/api/storefront",
  aws: "https://aws.amazon.com",
  framer: "https://www.framer.com/motion/",
  shadcn: "https://ui.shadcn.com",
  node: "https://nodejs.org",
  html: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  css: "https://developer.mozilla.org/en-US/docs/Web/CSS",
  git: "https://git-scm.com",
  gcp: "https://cloud.google.com",
};

export const skillIconColors: Record<string, string> = {
  reactnative: "#61DAFB",
  react: "#61DAFB",
  javascript: "#F7DF1E",
  typescript: "#3178C6",
  redux: "#764ABC",
  firebase: "#FFCA28",
  tailwind: "#06B6D4",
  github: "#f5f5f5",
  figma: "#F24E1E",
  postman: "#FF6C37",
  expo: "#f5f5f5",
  vite: "#646CFF",
  xcode: "#1575F9",
  androidstudio: "#3DDC84",
  graphql: "#E10098",
  shopify: "#95BF47",
  aws: "#FF9900",
  framer: "#0055FF",
  shadcn: "#f5f5f5",
  node: "#5FA04E",
  html: "#E34F26",
  css: "#1572B6",
  git: "#F05032",
  gcp: "#4285F4",
};

export const skillIconMap: Record<string, ReactElement> = {
  reactnative: <TbBrandReactNative />,
  react: <SiReact />,
  javascript: <SiJavascript />,
  typescript: <SiTypescript />,
  redux: <SiRedux />,
  firebase: <SiFirebase />,
  tailwind: <SiTailwindcss />,
  github: <SiGithub />,
  figma: <SiFigma />,
  postman: <SiPostman />,
  expo: <SiExpo />,
  vite: <SiVite />,
  api: <FiCode />,
  websocket: <FiZap />,
  performance: <FiZap />,
  animation: <MdAnimation />,
  cloud: <FiCloud />,
  tools: <FiTool />,
  xcode: <SiXcode />,
  androidstudio: <SiAndroidstudio />,
  graphql: <SiGraphql />,
  shopify: <SiShopify />,
  aws: <FiCloud />,
  framer: <SiFramer />,
  shadcn: <SiShadcnui />,
  node: <SiNodedotjs />,
  html: <SiHtml5 />,
  css: <SiCss />,
  git: <SiGit />,
  gcp: <SiGooglecloud />,
};
